sudo: false

addons:
    apt:
      packages:
       - make
       - cmake-data
       - cmake
  

# we compile a c++ project
language: cpp

compiler:
    - gcc
    - clang

os:
  - linux
  - osx
  
script:

  - mkdir build && cd build && cmake .. && make && make test
